version: "3.7"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-pass-in
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "db:/var/lib/postgresql/data"
    networks:
      - passin

  api-pass-in:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - 3001:3333
    environment:
      - PORT=3333
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - passin

networks:
  passin:
    driver: bridge

volumes:
  db:
