version: "3.7"

services:
  api-pass-in:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - 3001:3333
    environment:
      - PORT=3333
      - DATABASE_URL=file:./dev.db
