apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19zemJrdmpCSmZTaG1zdFNQakpSQHBhc3Npbi1jbHVzdGVyLWRvLXVzZXItMTYyNjk4OTItMC5jLmRiLm9uZGlnaXRhbG9jZWFuLmNvbToyNTA2MC9wYXNzaW4/c3NsbW9kZT1yZXF1aXJlCg==
